Adds UIUC fleet fuel consumption analysis
arfc/2020-fairhurst-hydrogen-production pull request #11
Opened 2020-01-26 21:28 UTC by robfairh

Closes #10

2020-01-26 21:55 UTC, katyhuff requested changes

2020-01-26 21:55 UTC, katyhuff commented on calculate.py
> +    ax.set_ylabel("Quantity (Gallons)", fontsize=14)
Something more specific here. 
```suggestion
    ax.set_ylabel(r'Fuel Consumed $\left(\frac{gal}{d}\right)$', fontsize=14)
```

2020-01-26 21:55 UTC, katyhuff commented on calculate.py
> +    ax.set_title('Fuel Consumption')
Something more specific here.

```suggestion
    ax.set_title('Daily {0} Fuel Consumption by the UIUC fleet'.format(fuel.capitalize()))
```

2020-01-27 04:01 UTC, samgdotson requested changes
Very minor style changes. You could run ``autopep8`` and it will format for you.

2020-01-27 04:01 UTC, samgdotson commented on calculate.py
> +""" This script analyses fuel consumption in a year.
```suggestion
""" 
This script analyses fuel consumption in a year.
```

2020-01-27 04:01 UTC, samgdotson commented on calculate.py
> +    """ Plots 'fuel'.
```suggestion
    """ 
    Plots 'fuel'.
```

2020-01-27 21:03 UTC, pep8speaks commented
Hello @robfairh! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`calculate.py`](https://github.com/arfc/2020-fairhurst-hydrogen-production/blob/dba0716ff7e59f9dab77a00bdb27b96bd1f72440/calculate.py):

> [Line 28:80](https://github.com/arfc/2020-fairhurst-hydrogen-production/blob/dba0716ff7e59f9dab77a00bdb27b96bd1f72440/calculate.py#L28): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)

2020-01-27 21:05 UTC, robfairh commented on calculate.py
> +""" This script analyses fuel consumption in a year.
Cool, thanks!

2020-01-27 21:29 UTC, robfairh commented
I committed both of your suggestions. Thank you!

2020-01-30 03:29 UTC, samgdotson approved these changes
Looks good

2020-01-30 03:36 UTC, merged